### ISSUE TITLE
Allow limiting resultset returned

### ISSUE THREAD

**Issue by bcipolli** [hakobera/embulk-input-mongodb#31]
I would like to use `limit()` to reduce the number of results returned in a single query. Is that possible now? I don't think so.

Would be happy to help contribute, if I could have some help on where to start!

**Comment by sakama** [comment]
Hi.

Currently this plugin doesn't support `limit()` as you're saying.
One idea to reduce import data size is using [incremental load](https://github.com/hakobera/embulk-input-mongodb#incremental-loading).

* First execution
`$ embulk run /path/to/config.yml -c diff.yml`
* Next execution
`$ embulk run /path/to/config.yml -c diff.yml`
Although you can't reduce import data size at first execution, plugin will get only diff data at next execution.

I think it's possible to implement `limit` and `skip` option. However we need to consider about confliction with incremental feature.
https://github.com/hakobera/embulk-input-mongodb/blob/master/src/main/java/org/embulk/input/mongodb/MongodbInputPlugin.java#L235

**Comment by sakama** [comment]
I sent PR to implement `limit` and `skip` options.
https://github.com/hakobera/embulk-input-mongodb/pull/32

**Comment by kamatama41** [comment]
@bcipolli @sakama 
Sorry for late response. I've released [v0.5.1](https://rubygems.org/gems/embulk-input-mongodb/versions/0.5.1) which includes #32. Please try it, thank you 🙏

**Comment by sakama** [comment]
Thanks 👍

**Comment by hakobera** [comment]
Fixed by #32
