### ISSUE TITLE
Incremental loading resets last_record field in the config file if no new record is uploaded

### ISSUE THREAD

**Issue by letianw91** [hakobera/embulk-input-mongodb#34]
Hi,

When I use incremental loading in the way specified in README, when there has been new records (as specified in "incremental field") since the last run, the plugin would correctly upload only the new records and writes the last record to the config file. However, if there are no new record since last run, the plugin would correctly upload nothing, but will also empty the last_record field of the config file. The would cause problems as the next time Embulk will upload everything again. Just wondering if this is a bug, a intended behavior, and whether there are any workarounds. Thanks! @friendofasquid

**Comment by sakama** [comment]
Hi. Thanks for your reporting.

> Just wondering if this is a bug, a intended behavior

This is a intended behavior.
Other Embulk plugins like embulk-input-mysql works as same.
As you're saying it might better to remain original `last_record` in diff.yml when stored data=0.

I think workaround is use something workflow tools.
We're also developing [digdag](https://github.com/treasure-data/digdag).

**Comment by friendofasquid** [comment]
Hi—we are Treasure Data customers. Wondering:

1 - if this is the behaviour of the Treasure Data connector powered by
Embulk

2 - In what scenario would you like to receive all your DB records on an
incremental update when there were no changes the previous run? We're
surprised this is intended behaviour, so we're wondering if we are thinking
about incremental loading incorrectly generally.

Thanks a lot. The connect has been extremely useful for getting data into
Treasure Data from behind our firewall.

**Comment by sakama** [comment]
Hi. I'm engineer of Treasure Data.

> 1 - if this is the behaviour of the Treasure Data connector powered by
Embulk

Yes, Treasure Data Data Connector is using perfectly same Embulk plugin with OSS one.

I checked other plugin's behavior again.
embulk-input-(s3|mysql) works as you expectes. Plugin will output same last record(=before execution) when there're no diff since previous run.

Then, I think  **this behavior is a bug** and need to be fixed.
I'll create another issue and try to fix it.

Thanks.

**Comment by letianw91** [comment]
@sakama Hi, any chance this will be fixed in a later release? Thank you!

**Comment by sakama** [comment]
@letianw91 Sorry to keep you waiting.
I'll try to fix this issue next week.

**Comment by letianw91** [comment]
No worries at all! We've been using this plugin heavily and thank you for your work in maintaining this!

**Comment by sakama** [comment]
This feature was released at v0.6.1.
I'll ask Treasure Data customer support team to notify you when it's available in TD.

Thanks.

**Comment by kamatama41** [comment]
@letianw91 
As @sakama commented, v0.6.1 was released.
Please reopen or create another issue if something is wrong to you, thank you.
