### ISSUE TITLE
Run an aggregate query

### ISSUE THREAD

**Issue by friendofasquid** [hakobera/embulk-input-mongodb#35]
Perhaps not in the spirit of embulk, but I would to send an aggregate query that looks like the below. Is this currently possible?

```
db.getCollection('users').aggregate([
    { $match: {
        "active_from":{"$lte":new Date() },
        $or: [
            { "active_until":{"$gt":new Date() }},
            { "active_until": null }
        ]
    } },
    { $group: {_id: "$account_id", total: {$sum: 1} } }
]);
```

**Comment by sakama** [comment]
> Is this currently possible?

Not supported for now.

Probably, it's possible to support aggregation pipeline.
```java
@Config("aggregation")
@ConfigDefault("null")
Optional<String> getAggregation();
...

Bson aggregationString = (Bson) JSON.parse(task.getAggregation().get());
List<Bson> aggregation = Arrays.asList(aggregationString);
collection = db.getCollection(task.getCollection(), Value.class)
        .withCodecRegistry(registry);
collection.aggregate(aggregation);
```
https://github.com/hakobera/embulk-input-mongodb/blob/v0.4.0/src/main/java/org/embulk/input/mongodb/MongodbInputPlugin.java#L185
https://github.com/hakobera/embulk-input-mongodb/blob/v0.4.0/src/main/java/org/embulk/input/mongodb/MongodbInputPlugin.java#L269

However, I don't think we can support complex query like your example.
We need to pass `List<Bson>` object to `aggregate()` method.
This means variable must be a
1. Valid JSON string - We need to `JSON.parse()` to convert into Bson object
2. Valid Bson

Your example doesn't satisfy 1.
```ruby
> irb
> require 'json'
> JSON.parse('{ $match: {"active_from":{"$lte":new Date() },$or: [{ "active_until":{"$gt":new Date() }},{ "active_until": null }]} },{ $group: {_id: "$account_id", total: {$sum: 1} } }')
JSON::ParserError: 784: unexpected token at '{ $match: {"active_from":{"$lte":new Date() },$or: [{ "active_until":{"$gt":new Date() }},{ "active_until": null }]} },{ $group: {_id: "$account_id", total: {$sum: 1} } }'
```

Similar problem was reported to `query` option https://github.com/hakobera/embulk-input-mongodb/issues/29
