### ISSUE TITLE
Update mongodb java driver to 3.6

### ISSUE THREAD

**Issue by letianw91** [hakobera/embulk-input-mongodb#38]
Hi,

Just wondering if there are plans to upgrade the mongodb java driver to 3.6. According to http://mongodb.github.io/mongo-java-driver/3.6/upgrading/, driver 3.6 is backward compatible with earlier versions, while the current version (3.2) in the plugin is not compatible with higher versions. Since our company is upgrading to mongo 3.6, it will be great if this plugin can be updated to latest version of the java driver. Thanks! 
 @friendofasquid

**Comment by sakama** [comment]
That sounds good to me.
I sent a PR https://github.com/hakobera/embulk-input-mongodb/pull/39

**Comment by letianw91** [comment]
This has been accomplished by the hardworking devs!
